### ISSUE TITLE
disappointment

### ISSUE THREAD

**Issue by devsnek** [qntm/base65536#14]
Hi there.

This lib was cool. Then you took it and made problems:
1) requiring stream makes it depend on node, which is kinda stupid.
2) both functions return some sort of join or concat on some chunks returned from streams but because streams are async and the operations could take amounts of time on large inputs this creates a rather obvious race condition.

The base of this issue is basically a request to revert a97f325f2b77e0a9e24b225ed1429e33eba76543, or reverse the dep chain, where streams can be used but they depend on base methods which don't require streams, and where there are no more race conditions.

**Comment by s100** [comment]
Can you elaborate?

**Comment by devsnek** [comment]
1) requiring stream makes it depend on node, which is kinda stupid.
2) both functions return `Buffer.concat(the chunks from the streams)` but because streams are async and could take amounts of time on large inputs, and because async is actually a thing (ikr!) this creates a rather obvious race condition.

**Comment by qntm** [comment]
1. Sorry about that. This library has been using `Buffer` since day one, didn't that already imply a dependency on Node.js?
2. I didn't realise that calling `stream.write` doesn't *always* call through synchronously to the `'data'` event listeners. I did wonder, but I assumed the behaviour would be consistently synchronous or consistently asynchronous, and when I tried it it was synchronous, so, my mistake. Is there a sensible way to wrap a streaming interface up so it can be called synchronously, or am I just going to have to implement this thing twice?

**Comment by devsnek** [comment]
I would recommend making the base methods support just taking a string and returning a string, like before the stream commit, and then the stream methods can just throw data through those

**Comment by qntm** [comment]
The base methods take a `String` and return a `Buffer` and vice-versa. I'm afraid this has been the case [since the earliest commit I can find](https://github.com/qntm/base65536/blob/25d6ea5104a16c24787fa1d8b4af836ba8bb6214/index.js#L52) in 2015. If I were to change this I would probably think about using [typed arrays](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays), which have support in browsers and Node.js.

**Comment by devsnek** [comment]
Sounds good to me

**Comment by s100** [comment]
I've been unable to reproduce the race condition you're talking about, and I have reason to believe that `stream.write` does in fact call synchronously through to the `'data'` event listeners, otherwise there would be a risk of chunks hitting those listeners out of order. Are you able to provide a failing test case?

**Comment by qntm** [comment]
I've been unable to reproduce the race condition you've described, and I suspect that it can't exist; `stream.write` surely has to call synchronously through to the `'data'` event listeners, otherwise there is a risk of chunks arriving out of order. Can you provide a failing test case?

**Comment by qntm** [comment]
There was no race condition with this module's usage of `stream` but it was a technically unneeded dependency and so this functionality has been split out as the new module [`base65536-stream`](https://github.com/qntm/base65536-stream).

Additionally, following a major version bump, this module now uses relatively environment-neutral `ArrayBuffer`s instead of Node.js-only `Buffer`s.
