### ISSUE TITLE
Question: Does it survive through simplification of chinese characters/japanese kanji?

### ISSUE THREAD

**Issue by user670** [qntm/base65536#15]
A website called Baidu (is a search engine) is known to automatically convert traditional Chinese or similar japanese Kanji to simplified Chinese, for example this character 僕 (if you fancy the meaning see en.wiktionary.org/wiki/僕 ) turns into 仆 ( en.wiktionary.org/wiki/仆 ). If base65536 can't survive through such change then it would be awkward to use in China (although still useable in other countries). So does it seem to survive through this? Or not?

**Comment by qntm** [comment]
Hi, excellent question.

Base65536 is designed to withstand all four forms of [Unicode normalization](https://en.wikipedia.org/wiki/Unicode_equivalence#Normalization): NFC, NFD, NFKC and NFKD. If Baidu only applies Unicode normalization, then we are fine.

But it looks to me as if "僕" survives Unicode normalization unchanged, whereas Baidu converts it to "仆" - which means that the transformation Baidu applies is *not* ordinary Unicode normalization. So I need to ask some follow-up questions.

* What exactly is the use case here? I assume that you want to put a Base65536 text into the Baidu search engine so that you can find instances of the Base65536 text online. Is that correct? I will be honest: this is not a use case for Base65536 which I anticipated. It's possible that Base65536 will not 
* When does Baidu apply its transformation? At web page spidering time? At search text input time? Both? If it's both, then we may still be fine. If your search text is "abc" and the web page contains "abc", it doesn't matter that Baidu transformed your search text into "def" and the web page into "def" too, there will still be a match between the two "def" strings. I think. But it might not be as simple as that.
* Is this transformation documented anywhere? For example, is there a complete list of characters which are transformed? Is there a complete list of characters which are *not* transformed? Is the transformation only applied to legible, comprehensible text (which Base65536 almost always is not)?

When I searched for "驨ꍬ啯𒁷ꍲᕤ" ("hello world"), it found [the `base65536` NPM page](https://www.npmjs.com/package/base65536) and several other results, and the text match was highlighted correctly.

I'm cautiously optimistic that this will work, but I can't provide any guarantees until I know more about how Baidu works - and even then, Baidu is not under my control, so I can't really guarantee anything about its searching behaviour, any more than I can about Google's.
