### ISSUE TITLE
Compare to base-122

### ISSUE THREAD

**Issue by andersk** [qntm/base65536#8]
The comparison table leaves out [base-122](http://blog.kevinalbs.com/base122), which is 87.5% efficient in UTF-8, better than anything listed there.

**Comment by qntm** [comment]
The encodings comparison table is not intended to be exhaustive so I'll probably leave this for now...

In any case, Base-122 seems to make heavy use of dangerous control characters, which means it can't compete with any of the other listed encodings because it simply isn't suitable for the same purposes. Most significantly, you can't put ASCII control characters like SOH, STX, ... in a Tweet.
